/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'atype' : AssignmentType,
  'createdAt' : Timestamp,
  'sessionId' : SessionId,
}
export type AssignmentStatus = { 'graded' : null } |
  { 'submitted' : null } |
  { 'pending' : null };
export type AssignmentType = { 'mcq' : null } |
  { 'poll' : null } |
  { 'writing' : null } |
  { 'drawing' : null };
export interface Badge { 'id' : bigint, 'title' : string }
export interface ChapterProgress {
  'completed' : boolean,
  'chapterId' : bigint,
  'score' : bigint,
}
export interface Choice { 'id' : bigint, 'text' : string, 'correct' : boolean }
export interface ExamScore {
  'total' : bigint,
  'level' : bigint,
  'score' : bigint,
}
export interface GameScore {
  'total' : bigint,
  'score' : bigint,
  'boxId' : bigint,
}
export interface Question {
  'id' : bigint,
  'explanation' : string,
  'text' : string,
  'qtype' : QuestionType,
  'chapterId' : [] | [bigint],
  'level' : [] | [bigint],
  'boxId' : [] | [bigint],
  'choices' : Array<Choice>,
}
export type QuestionType = { 'exam' : null } |
  { 'game' : null } |
  { 'grammar' : null } |
  { 'writing' : null } |
  { 'chapter' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export interface Session {
  'id' : SessionId,
  'status' : SessionStatus,
  'createdAt' : Timestamp,
  'teacherId' : UserId,
}
export type SessionId = string;
export type SessionStatus = { 'active' : null } |
  { 'ended' : null };
export interface Student {
  'userId' : UserId,
  'name' : string,
  'badges' : Array<Badge>,
  'joinedAt' : Timestamp,
  'chapterProgress' : Array<ChapterProgress>,
  'gameScores' : Array<GameScore>,
  'unlockedChars' : Array<bigint>,
  'examScores' : Array<ExamScore>,
  'sessionId' : SessionId,
  'className' : string,
  'points' : bigint,
}
export interface SubmissionPublic {
  'status' : AssignmentStatus,
  'userId' : UserId,
  'submittedAt' : Timestamp,
  'feedback' : string,
  'answer' : string,
  'grade' : [] | [bigint],
  'assignmentId' : bigint,
  'sessionId' : SessionId,
}
export type Timestamp = bigint;
export type UserId = string;
export interface _SERVICE {
  'addQuestion' : ActorMethod<[Question], bigint>,
  'awardBadge' : ActorMethod<[UserId, Badge], Result>,
  'classCompletion' : ActorMethod<[SessionId], bigint>,
  'createAssignment' : ActorMethod<
    [SessionId, string, AssignmentType, string],
    bigint
  >,
  'createSession' : ActorMethod<[UserId], SessionId>,
  'deleteAssignment' : ActorMethod<[bigint], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'endSession' : ActorMethod<[SessionId, UserId], Result>,
  'getLeaderboard' : ActorMethod<[SessionId], Array<Student>>,
  'getSession' : ActorMethod<[SessionId], [] | [Session]>,
  'getStudent' : ActorMethod<[UserId], [] | [Student]>,
  'getSubmissions' : ActorMethod<[bigint], Array<SubmissionPublic>>,
  'gradeSubmission' : ActorMethod<[bigint, UserId, bigint, string], Result>,
  'grantPoints' : ActorMethod<[UserId, bigint], Result_1>,
  'joinSession' : ActorMethod<[SessionId, UserId, string, string], Result>,
  'listAssignments' : ActorMethod<[SessionId], Array<Assignment>>,
  'listQuestions' : ActorMethod<
    [[] | [QuestionType], [] | [bigint], [] | [bigint], [] | [bigint]],
    Array<Question>
  >,
  'listStudents' : ActorMethod<[SessionId], Array<Student>>,
  'mySubmissions' : ActorMethod<[UserId], Array<SubmissionPublic>>,
  'saveDrawing' : ActorMethod<[UserId, string], Result>,
  'saveNotes' : ActorMethod<[UserId, string], Result>,
  'submitAssignment' : ActorMethod<[bigint, UserId, SessionId, string], Result>,
  'submitChapterProgress' : ActorMethod<[UserId, ChapterProgress], Result>,
  'submitExamScore' : ActorMethod<[UserId, ExamScore], Result>,
  'submitGameScore' : ActorMethod<[UserId, GameScore], Result>,
  'updateQuestion' : ActorMethod<[Question], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];