/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionType = IDL.Variant({
  'exam' : IDL.Null,
  'game' : IDL.Null,
  'grammar' : IDL.Null,
  'writing' : IDL.Null,
  'chapter' : IDL.Null,
});
export const Choice = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'correct' : IDL.Bool,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'qtype' : QuestionType,
  'chapterId' : IDL.Opt(IDL.Nat),
  'level' : IDL.Opt(IDL.Nat),
  'boxId' : IDL.Opt(IDL.Nat),
  'choices' : IDL.Vec(Choice),
});
export const UserId = IDL.Text;
export const Badge = IDL.Record({ 'id' : IDL.Nat, 'title' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const SessionId = IDL.Text;
export const AssignmentType = IDL.Variant({
  'mcq' : IDL.Null,
  'poll' : IDL.Null,
  'writing' : IDL.Null,
  'drawing' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ChapterProgress = IDL.Record({
  'completed' : IDL.Bool,
  'chapterId' : IDL.Nat,
  'score' : IDL.Nat,
});
export const GameScore = IDL.Record({
  'total' : IDL.Nat,
  'score' : IDL.Nat,
  'boxId' : IDL.Nat,
});
export const ExamScore = IDL.Record({
  'total' : IDL.Nat,
  'level' : IDL.Nat,
  'score' : IDL.Nat,
});
export const Student = IDL.Record({
  'userId' : UserId,
  'name' : IDL.Text,
  'badges' : IDL.Vec(Badge),
  'joinedAt' : Timestamp,
  'chapterProgress' : IDL.Vec(ChapterProgress),
  'gameScores' : IDL.Vec(GameScore),
  'unlockedChars' : IDL.Vec(IDL.Nat),
  'examScores' : IDL.Vec(ExamScore),
  'sessionId' : SessionId,
  'className' : IDL.Text,
  'points' : IDL.Nat,
});
export const SessionStatus = IDL.Variant({
  'active' : IDL.Null,
  'ended' : IDL.Null,
});
export const Session = IDL.Record({
  'id' : SessionId,
  'status' : SessionStatus,
  'createdAt' : Timestamp,
  'teacherId' : UserId,
});
export const AssignmentStatus = IDL.Variant({
  'graded' : IDL.Null,
  'submitted' : IDL.Null,
  'pending' : IDL.Null,
});
export const SubmissionPublic = IDL.Record({
  'status' : AssignmentStatus,
  'userId' : UserId,
  'submittedAt' : Timestamp,
  'feedback' : IDL.Text,
  'answer' : IDL.Text,
  'grade' : IDL.Opt(IDL.Nat),
  'assignmentId' : IDL.Nat,
  'sessionId' : SessionId,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Assignment = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'atype' : AssignmentType,
  'createdAt' : Timestamp,
  'sessionId' : SessionId,
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func([Question], [IDL.Nat], []),
  'awardBadge' : IDL.Func([UserId, Badge], [Result], []),
  'classCompletion' : IDL.Func([SessionId], [IDL.Nat], ['query']),
  'createAssignment' : IDL.Func(
      [SessionId, IDL.Text, AssignmentType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createSession' : IDL.Func([UserId], [SessionId], []),
  'deleteAssignment' : IDL.Func([IDL.Nat], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'endSession' : IDL.Func([SessionId, UserId], [Result], []),
  'getLeaderboard' : IDL.Func([SessionId], [IDL.Vec(Student)], ['query']),
  'getSession' : IDL.Func([SessionId], [IDL.Opt(Session)], ['query']),
  'getStudent' : IDL.Func([UserId], [IDL.Opt(Student)], ['query']),
  'getSubmissions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SubmissionPublic)],
      ['query'],
    ),
  'gradeSubmission' : IDL.Func(
      [IDL.Nat, UserId, IDL.Nat, IDL.Text],
      [Result],
      [],
    ),
  'grantPoints' : IDL.Func([UserId, IDL.Nat], [Result_1], []),
  'joinSession' : IDL.Func(
      [SessionId, UserId, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'listAssignments' : IDL.Func([SessionId], [IDL.Vec(Assignment)], ['query']),
  'listQuestions' : IDL.Func(
      [
        IDL.Opt(QuestionType),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'listStudents' : IDL.Func([SessionId], [IDL.Vec(Student)], ['query']),
  'mySubmissions' : IDL.Func([UserId], [IDL.Vec(SubmissionPublic)], ['query']),
  'saveDrawing' : IDL.Func([UserId, IDL.Text], [Result], []),
  'saveNotes' : IDL.Func([UserId, IDL.Text], [Result], []),
  'submitAssignment' : IDL.Func(
      [IDL.Nat, UserId, SessionId, IDL.Text],
      [Result],
      [],
    ),
  'submitChapterProgress' : IDL.Func([UserId, ChapterProgress], [Result], []),
  'submitExamScore' : IDL.Func([UserId, ExamScore], [Result], []),
  'submitGameScore' : IDL.Func([UserId, GameScore], [Result], []),
  'updateQuestion' : IDL.Func([Question], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionType = IDL.Variant({
    'exam' : IDL.Null,
    'game' : IDL.Null,
    'grammar' : IDL.Null,
    'writing' : IDL.Null,
    'chapter' : IDL.Null,
  });
  const Choice = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'correct' : IDL.Bool,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'qtype' : QuestionType,
    'chapterId' : IDL.Opt(IDL.Nat),
    'level' : IDL.Opt(IDL.Nat),
    'boxId' : IDL.Opt(IDL.Nat),
    'choices' : IDL.Vec(Choice),
  });
  const UserId = IDL.Text;
  const Badge = IDL.Record({ 'id' : IDL.Nat, 'title' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const SessionId = IDL.Text;
  const AssignmentType = IDL.Variant({
    'mcq' : IDL.Null,
    'poll' : IDL.Null,
    'writing' : IDL.Null,
    'drawing' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ChapterProgress = IDL.Record({
    'completed' : IDL.Bool,
    'chapterId' : IDL.Nat,
    'score' : IDL.Nat,
  });
  const GameScore = IDL.Record({
    'total' : IDL.Nat,
    'score' : IDL.Nat,
    'boxId' : IDL.Nat,
  });
  const ExamScore = IDL.Record({
    'total' : IDL.Nat,
    'level' : IDL.Nat,
    'score' : IDL.Nat,
  });
  const Student = IDL.Record({
    'userId' : UserId,
    'name' : IDL.Text,
    'badges' : IDL.Vec(Badge),
    'joinedAt' : Timestamp,
    'chapterProgress' : IDL.Vec(ChapterProgress),
    'gameScores' : IDL.Vec(GameScore),
    'unlockedChars' : IDL.Vec(IDL.Nat),
    'examScores' : IDL.Vec(ExamScore),
    'sessionId' : SessionId,
    'className' : IDL.Text,
    'points' : IDL.Nat,
  });
  const SessionStatus = IDL.Variant({
    'active' : IDL.Null,
    'ended' : IDL.Null,
  });
  const Session = IDL.Record({
    'id' : SessionId,
    'status' : SessionStatus,
    'createdAt' : Timestamp,
    'teacherId' : UserId,
  });
  const AssignmentStatus = IDL.Variant({
    'graded' : IDL.Null,
    'submitted' : IDL.Null,
    'pending' : IDL.Null,
  });
  const SubmissionPublic = IDL.Record({
    'status' : AssignmentStatus,
    'userId' : UserId,
    'submittedAt' : Timestamp,
    'feedback' : IDL.Text,
    'answer' : IDL.Text,
    'grade' : IDL.Opt(IDL.Nat),
    'assignmentId' : IDL.Nat,
    'sessionId' : SessionId,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Assignment = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'atype' : AssignmentType,
    'createdAt' : Timestamp,
    'sessionId' : SessionId,
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func([Question], [IDL.Nat], []),
    'awardBadge' : IDL.Func([UserId, Badge], [Result], []),
    'classCompletion' : IDL.Func([SessionId], [IDL.Nat], ['query']),
    'createAssignment' : IDL.Func(
        [SessionId, IDL.Text, AssignmentType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createSession' : IDL.Func([UserId], [SessionId], []),
    'deleteAssignment' : IDL.Func([IDL.Nat], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'endSession' : IDL.Func([SessionId, UserId], [Result], []),
    'getLeaderboard' : IDL.Func([SessionId], [IDL.Vec(Student)], ['query']),
    'getSession' : IDL.Func([SessionId], [IDL.Opt(Session)], ['query']),
    'getStudent' : IDL.Func([UserId], [IDL.Opt(Student)], ['query']),
    'getSubmissions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SubmissionPublic)],
        ['query'],
      ),
    'gradeSubmission' : IDL.Func(
        [IDL.Nat, UserId, IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
    'grantPoints' : IDL.Func([UserId, IDL.Nat], [Result_1], []),
    'joinSession' : IDL.Func(
        [SessionId, UserId, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'listAssignments' : IDL.Func([SessionId], [IDL.Vec(Assignment)], ['query']),
    'listQuestions' : IDL.Func(
        [
          IDL.Opt(QuestionType),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'listStudents' : IDL.Func([SessionId], [IDL.Vec(Student)], ['query']),
    'mySubmissions' : IDL.Func(
        [UserId],
        [IDL.Vec(SubmissionPublic)],
        ['query'],
      ),
    'saveDrawing' : IDL.Func([UserId, IDL.Text], [Result], []),
    'saveNotes' : IDL.Func([UserId, IDL.Text], [Result], []),
    'submitAssignment' : IDL.Func(
        [IDL.Nat, UserId, SessionId, IDL.Text],
        [Result],
        [],
      ),
    'submitChapterProgress' : IDL.Func([UserId, ChapterProgress], [Result], []),
    'submitExamScore' : IDL.Func([UserId, ExamScore], [Result], []),
    'submitGameScore' : IDL.Func([UserId, GameScore], [Result], []),
    'updateQuestion' : IDL.Func([Question], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };