/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type SessionId = string;
export interface ChapterProgress {
    completed: boolean;
    chapterId: bigint;
    score: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface Badge {
    id: bigint;
    title: string;
}
export interface ExamScore {
    total: bigint;
    level: bigint;
    score: bigint;
}
export type UserId = string;
export interface Session {
    id: SessionId;
    status: SessionStatus;
    createdAt: Timestamp;
    teacherId: UserId;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface GameScore {
    total: bigint;
    score: bigint;
    boxId: bigint;
}
export interface Choice {
    id: bigint;
    text: string;
    correct: boolean;
}
export interface Assignment {
    id: bigint;
    title: string;
    content: string;
    atype: AssignmentType;
    createdAt: Timestamp;
    sessionId: SessionId;
}
export interface SubmissionPublic {
    status: AssignmentStatus;
    userId: UserId;
    submittedAt: Timestamp;
    feedback: string;
    answer: string;
    grade?: bigint;
    assignmentId: bigint;
    sessionId: SessionId;
}
export interface Question {
    id: bigint;
    explanation: string;
    text: string;
    qtype: QuestionType;
    chapterId?: bigint;
    level?: bigint;
    boxId?: bigint;
    choices: Array<Choice>;
}
export interface Student {
    userId: UserId;
    name: string;
    badges: Array<Badge>;
    joinedAt: Timestamp;
    chapterProgress: Array<ChapterProgress>;
    gameScores: Array<GameScore>;
    unlockedChars: Array<bigint>;
    examScores: Array<ExamScore>;
    sessionId: SessionId;
    className: string;
    points: bigint;
}
export enum AssignmentStatus {
    graded = "graded",
    submitted = "submitted",
    pending = "pending"
}
export enum AssignmentType {
    mcq = "mcq",
    poll = "poll",
    writing = "writing",
    drawing = "drawing"
}
export enum QuestionType {
    exam = "exam",
    game = "game",
    grammar = "grammar",
    writing = "writing",
    chapter = "chapter"
}
export enum SessionStatus {
    active = "active",
    ended = "ended"
}
export interface backendInterface {
    addQuestion(q: Question): Promise<bigint>;
    awardBadge(userId: UserId, badge: Badge): Promise<Result>;
    classCompletion(sessionId: SessionId): Promise<bigint>;
    createAssignment(sessionId: SessionId, title: string, atype: AssignmentType, content: string): Promise<bigint>;
    createSession(teacherId: UserId): Promise<SessionId>;
    deleteAssignment(id: bigint): Promise<void>;
    deleteQuestion(id: bigint): Promise<void>;
    endSession(sessionId: SessionId, teacherId: UserId): Promise<Result>;
    getLeaderboard(sessionId: SessionId): Promise<Array<Student>>;
    getSession(sessionId: SessionId): Promise<Session | null>;
    getStudent(userId: UserId): Promise<Student | null>;
    getSubmissions(assignmentId: bigint): Promise<Array<SubmissionPublic>>;
    gradeSubmission(assignmentId: bigint, userId: UserId, grade: bigint, feedback: string): Promise<Result>;
    grantPoints(userId: UserId, delta: bigint): Promise<Result_1>;
    joinSession(sessionId: SessionId, userId: UserId, name: string, className: string): Promise<Result>;
    listAssignments(sessionId: SessionId): Promise<Array<Assignment>>;
    listQuestions(qtype: QuestionType | null, chapterId: bigint | null, level: bigint | null, boxId: bigint | null): Promise<Array<Question>>;
    listStudents(sessionId: SessionId): Promise<Array<Student>>;
    mySubmissions(userId: UserId): Promise<Array<SubmissionPublic>>;
    saveDrawing(userId: UserId, data: string): Promise<Result>;
    saveNotes(userId: UserId, notes: string): Promise<Result>;
    submitAssignment(assignmentId: bigint, userId: UserId, sessionId: SessionId, answer: string): Promise<Result>;
    submitChapterProgress(userId: UserId, progress: ChapterProgress): Promise<Result>;
    submitExamScore(userId: UserId, score: ExamScore): Promise<Result>;
    submitGameScore(userId: UserId, score: GameScore): Promise<Result>;
    updateQuestion(q: Question): Promise<Result>;
}
import type { Assignment as _Assignment, AssignmentStatus as _AssignmentStatus, AssignmentType as _AssignmentType, Choice as _Choice, Question as _Question, QuestionType as _QuestionType, Result as _Result, Result_1 as _Result_1, Session as _Session, SessionId as _SessionId, SessionStatus as _SessionStatus, Student as _Student, SubmissionPublic as _SubmissionPublic, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addQuestion(arg0: Question): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(to_candid_Question_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(to_candid_Question_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async awardBadge(arg0: UserId, arg1: Badge): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.awardBadge(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardBadge(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async classCompletion(arg0: SessionId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.classCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.classCompletion(arg0);
            return result;
        }
    }
    async createAssignment(arg0: SessionId, arg1: string, arg2: AssignmentType, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(arg0, arg1, to_candid_AssignmentType_n7(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(arg0, arg1, to_candid_AssignmentType_n7(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createSession(arg0: UserId): Promise<SessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0);
            return result;
        }
    }
    async deleteAssignment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssignment(arg0);
            return result;
        }
    }
    async deleteQuestion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async endSession(arg0: SessionId, arg1: UserId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.endSession(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endSession(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: SessionId): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return result;
        }
    }
    async getSession(arg0: SessionId): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: UserId): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissions(arg0: bigint): Promise<Array<SubmissionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissions(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissions(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async gradeSubmission(arg0: bigint, arg1: UserId, arg2: bigint, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.gradeSubmission(arg0, arg1, arg2, arg3);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gradeSubmission(arg0, arg1, arg2, arg3);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantPoints(arg0: UserId, arg1: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.grantPoints(arg0, arg1);
                return from_candid_Result_1_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantPoints(arg0, arg1);
            return from_candid_Result_1_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinSession(arg0: SessionId, arg1: UserId, arg2: string, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSession(arg0, arg1, arg2, arg3);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSession(arg0, arg1, arg2, arg3);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAssignments(arg0: SessionId): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssignments(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssignments(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuestions(arg0: QuestionType | null, arg1: bigint | null, arg2: bigint | null, arg3: bigint | null): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuestions(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuestions(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudents(arg0: SessionId): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents(arg0);
            return result;
        }
    }
    async mySubmissions(arg0: UserId): Promise<Array<SubmissionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.mySubmissions(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mySubmissions(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDrawing(arg0: UserId, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDrawing(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDrawing(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveNotes(arg0: UserId, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNotes(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNotes(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAssignment(arg0: bigint, arg1: UserId, arg2: SessionId, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssignment(arg0, arg1, arg2, arg3);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssignment(arg0, arg1, arg2, arg3);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitChapterProgress(arg0: UserId, arg1: ChapterProgress): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitChapterProgress(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitChapterProgress(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitExamScore(arg0: UserId, arg1: ExamScore): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitExamScore(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitExamScore(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitGameScore(arg0: UserId, arg1: GameScore): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGameScore(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGameScore(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateQuestion(arg0: Question): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(to_candid_Question_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(to_candid_Question_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AssignmentStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentStatus): AssignmentStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_AssignmentType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentType): AssignmentType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Assignment_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Assignment {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionPublic_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionPublic): SubmissionPublic {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : from_candid_Session_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    status: _SessionStatus;
    createdAt: _Timestamp;
    teacherId: _UserId;
}): {
    id: SessionId;
    status: SessionStatus;
    createdAt: Timestamp;
    teacherId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_SessionStatus_n12(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        teacherId: value.teacherId
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AssignmentStatus;
    userId: _UserId;
    submittedAt: _Timestamp;
    feedback: string;
    answer: string;
    grade: [] | [bigint];
    assignmentId: bigint;
    sessionId: _SessionId;
}): {
    status: AssignmentStatus;
    userId: UserId;
    submittedAt: Timestamp;
    feedback: string;
    answer: string;
    grade?: bigint;
    assignmentId: bigint;
    sessionId: SessionId;
} {
    return {
        status: from_candid_AssignmentStatus_n18(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        submittedAt: value.submittedAt,
        feedback: value.feedback,
        answer: value.answer,
        grade: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.grade)),
        assignmentId: value.assignmentId,
        sessionId: value.sessionId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    atype: _AssignmentType;
    createdAt: _Timestamp;
    sessionId: _SessionId;
}): {
    id: bigint;
    title: string;
    content: string;
    atype: AssignmentType;
    createdAt: Timestamp;
    sessionId: SessionId;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        atype: from_candid_AssignmentType_n26(_uploadFile, _downloadFile, value.atype),
        createdAt: value.createdAt,
        sessionId: value.sessionId
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    explanation: string;
    text: string;
    qtype: _QuestionType;
    chapterId: [] | [bigint];
    level: [] | [bigint];
    boxId: [] | [bigint];
    choices: Array<_Choice>;
}): {
    id: bigint;
    explanation: string;
    text: string;
    qtype: QuestionType;
    chapterId?: bigint;
    level?: bigint;
    boxId?: bigint;
    choices: Array<Choice>;
} {
    return {
        id: value.id,
        explanation: value.explanation,
        text: value.text,
        qtype: from_candid_QuestionType_n33(_uploadFile, _downloadFile, value.qtype),
        chapterId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.chapterId)),
        level: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.level)),
        boxId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.boxId)),
        choices: value.choices
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    ended: null;
}): SessionStatus {
    return "active" in value ? SessionStatus.active : "ended" in value ? SessionStatus.ended : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    graded: null;
} | {
    submitted: null;
} | {
    pending: null;
}): AssignmentStatus {
    return "graded" in value ? AssignmentStatus.graded : "submitted" in value ? AssignmentStatus.submitted : "pending" in value ? AssignmentStatus.pending : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mcq: null;
} | {
    poll: null;
} | {
    writing: null;
} | {
    drawing: null;
}): AssignmentType {
    return "mcq" in value ? AssignmentType.mcq : "poll" in value ? AssignmentType.poll : "writing" in value ? AssignmentType.writing : "drawing" in value ? AssignmentType.drawing : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exam: null;
} | {
    game: null;
} | {
    grammar: null;
} | {
    writing: null;
} | {
    chapter: null;
}): QuestionType {
    return "exam" in value ? QuestionType.exam : "game" in value ? QuestionType.game : "grammar" in value ? QuestionType.grammar : "writing" in value ? QuestionType.writing : "chapter" in value ? QuestionType.chapter : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubmissionPublic>): Array<SubmissionPublic> {
    return value.map((x)=>from_candid_SubmissionPublic_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Array<Assignment> {
    return value.map((x)=>from_candid_Assignment_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n31(_uploadFile, _downloadFile, x));
}
function to_candid_AssignmentType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentType): _AssignmentType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType | null): [] | [_QuestionType] {
    return value === null ? candid_none() : candid_some(to_candid_QuestionType_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    explanation: string;
    text: string;
    qtype: QuestionType;
    chapterId?: bigint;
    level?: bigint;
    boxId?: bigint;
    choices: Array<Choice>;
}): {
    id: bigint;
    explanation: string;
    text: string;
    qtype: _QuestionType;
    chapterId: [] | [bigint];
    level: [] | [bigint];
    boxId: [] | [bigint];
    choices: Array<_Choice>;
} {
    return {
        id: value.id,
        explanation: value.explanation,
        text: value.text,
        qtype: to_candid_QuestionType_n3(_uploadFile, _downloadFile, value.qtype),
        chapterId: value.chapterId ? candid_some(value.chapterId) : candid_none(),
        level: value.level ? candid_some(value.level) : candid_none(),
        boxId: value.boxId ? candid_some(value.boxId) : candid_none(),
        choices: value.choices
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    exam: null;
} | {
    game: null;
} | {
    grammar: null;
} | {
    writing: null;
} | {
    chapter: null;
} {
    return value == QuestionType.exam ? {
        exam: null
    } : value == QuestionType.game ? {
        game: null
    } : value == QuestionType.grammar ? {
        grammar: null
    } : value == QuestionType.writing ? {
        writing: null
    } : value == QuestionType.chapter ? {
        chapter: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentType): {
    mcq: null;
} | {
    poll: null;
} | {
    writing: null;
} | {
    drawing: null;
} {
    return value == AssignmentType.mcq ? {
        mcq: null
    } : value == AssignmentType.poll ? {
        poll: null
    } : value == AssignmentType.writing ? {
        writing: null
    } : value == AssignmentType.drawing ? {
        drawing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
